[theme]
# Using light as the base theme
base = "light"
primaryColor = "#0077FF"  # Blue accent color
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for sidebar
textColor = "#262730"  # Dark text 